stages:
  - baseline

baseline-image:
  stage: baseline
  only:
    refs:
      - /^(v[0-9][.][0-9][.]x|develop)?$/
  image: atulabhi/kops:v10
  before_script: []  
  script:
     - pwd
     - apt-get update
     - apt-get install --yes git-core
     - git config --global user.name "OpenEBS CI Bot"
     - git config --global user.email openebscibot@openebs.io
     - export BRANCH=${CI_COMMIT_REF_NAME}
     - echo $BRANCH
     - export COMMIT=${CI_COMMIT_SHORT_SHA}
     - echo $COMMIT
     - git clone https://github.com/$REPO/e2e-infrastructure.git
     - if [[ "$BRANCH" == "develop" ]] ; then git checkout master ; else git checkout $BRANCH ; fi
     - cd e2e-infrastructure/baseline
     - ansible-playbook commit-writer.yml --extra-vars "branch=$BRANCH repo=$CI_PROJECT_NAME commit=$COMMIT"
     - git status
     - git add baseline
     - git status
     - git commit -m "updated $CI_PROJECT_NAME commit:$COMMIT"
     - git push  https://$user:$pass@github.com/$REPO/e2e-infrastructure.git --all
     - if [[ "$BRANCH" == "develop" ]] ; then export INFRA="master" ; else export INFRA=$BRANCH ; fi
     - curl -X POST -F variables[INFRA_BRANCH]=$INFRA -F token=$OPENSHIFT -F ref=OpenEBS-base https://gitlab.openebs.ci/api/v4/projects/15/trigger/pipeline
